name: cd 

on: 
  workflow_run: 
    workflows: ["ci"]
    types: 
      - completed
  
  workflow_dispatch: 


jobs: 
  cd: 
    if: ${{github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy started
        run: echo "CD pipe line started"
  