name: ci

on: 
  push: 
    branches: 
      - main
      - "feature/**"

  pull_request: 
    branches: 
      - main

jobs: 
  init: 
    name: initialise
    runs-on: ubuntu-latest
    steps:
      - name: Initial step
        run: echo "Initialising CI"


  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist/  


    