name: ci

on: 
  push: 
    branches: 
      - main
      - "feature/**"

  pull_request: 
    branches: 
      - main
  
  workflow_dispatch: 

jobs: 
  init: 
    name: initialise
    runs-on: ubuntu-latest
    steps:
      - name: Initial step
        run: echo "Initialising CI"


  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

      - name: Build Project
        run: npm run build

      - name: Set build date
        id: build_date
        env: 
          GH_TOKEN: ${{ github.token }}
        run: |
          DATE: DATE=$(TZ=Asia/Kolkata date +%Y%m%d)
          RUN_COUNT=$(gh run list \
            --workflow ci.yml \
            --limit 1000 \
            --json createdAt \
            --jq "[.[] | select((.createdAt | fromdateiso8601) >= (now - 19800 | floor))] | length")
          RUN_COUNT=$((RUN_COUNT + 1))

          echo "version=${DATE}.${RUN_COUNT}" >> "$GITHUB_OUTPUT"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.build_date.outputs.version}}
          path: dist/  


    